### Creates a Bin
POST http://localhost:3000/api/bins HTTP/1.1

### Gets All Bins
GET http://localhost:3000/api/bins HTTP/1.1

### Gets Bin By Id
GET http://localhost:3000/api/bins/63055364e0810388f2118f83 HTTP/1.1

### Deletes Bin By Id
DELETE http://localhost:3000/api/bins/63055ca1604a3d983c0ce8c7 HTTP/1.1

### Deletes All Bins
DELETE http://localhost:3000/api/bins HTTP/1.1

